@startuml conception


class MonteCarlo {
    + option : Option 
    + model : BlackScholesModel
    + fixingDatesNumber : int N
    + sampleNumber : int M
    + price()
    
    
}


abstract class Option {
    + Maturity : Date 
    + strike : double 
    + type :  OptionType 
    + abstract payOff 
}

Enum OptionType {
    + Basket : 0 
    + Asian : 1 
    + Performance : 2
}

class OptionBasket {
    + override payOff()
}

class OptionAsian {
    + override payOff()
}

class OptionPerformance {
    + override payOff()
}

Option <|-- OptionBasket 
Option <|-- OptionAsian 
Option <|-- OptionPerformance 


abstract class Model {

}

class BlackScholesModel {
    + interesetRate : double 
    + volatility : double[]
    + spot : double[]
    + optionSize : double
    + payoffCoeffcients : double[] 
    + correlation : double 
    + headingDatesNumber : int 
    + fdStep  : int 
    + void asset()
}

Model <|-- BlackScholesModel

@enduml 